using System.Collections.Generic;
using System.Security.Claims;
using Microsoft.AspNet.Identity;
using RoadCalc.Models.Entities;
using RoadCalc.Models.Identity;

namespace RoadCalc.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<RoadCalc.Context.EstradasContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(RoadCalc.Context.EstradasContext context)
        {
            context.ClasseDeProjetos.AddOrUpdate(x => x.Id,
                 new ClasseDeProjeto()
                 {
                     Id = 1,
                     Nome = "0",
                     Caracteristicas = "Via Expressa - Controle Total de Acessos",
                     CritClassTecnica = "Decisão Administrativa",
                     Relevo = ClasseDeProjeto.TiposDeRelevo.Plano,
                     VelProjeto = 120,
                     VelDirMin = 120,
                     DistMinVisbParMinD = 310,
                     DistMinVisbParMinA = 205,
                     DistMinVisbUltra = 0,
                     RaioMinSupEleMax = 540,
                     SupEleMax = 10,
                     RampaMax = 3,
                     KCxMinD = 233,
                     KCxMinA = 102,
                     KCvMinD = 80,
                     KCvMinA = 50,
                     LargFxTrans = 3.60,
                     LargAcoExtD = 0,
                     LargAcoExtA = 3.50,
                     LargAcoIntDuasFxMin = 0.60,
                     LargAcoIntDuasFxMax = 1.20,
                     LargAcoIntTresFxMin = 2.50,
                     LargAcoIntTresFxMax = 3.00,
                     LargAcoIntQuatroFxMin = 3.00,
                     LargAcoIntQuatroFxMax = 3.00,
                     GabVertD = 0,
                     GabVertA = 5.50,
                     AfastMinBordAcoObI = 1.50,
                     LargCantCentDMin = 10,
                     LargCantCentDMax = 18,
                     LargCantCentNMin = 6,
                     LargCantCentNMax = 7,
                     LargCantCentAMin = 3,
                     LargCantCentAMax = 7
                 },
                 new ClasseDeProjeto()
                 {
                     Id = 2,
                     Nome = "0",
                     Caracteristicas = "Via Expressa - Controle Total de Acessos",
                     CritClassTecnica = "Decisão Administrativa",
                     Relevo = ClasseDeProjeto.TiposDeRelevo.Ondulado,
                     VelProjeto = 100,
                     VelDirMin = 100,
                     DistMinVisbParMinD = 210,
                     DistMinVisbParMinA = 155,
                     DistMinVisbUltra = 0,
                     RaioMinSupEleMax = 345,
                     SupEleMax = 10,
                     RampaMax = 4,
                     KCxMinD = 107,
                     KCxMinA = 58,
                     KCvMinD = 52,
                     KCvMinA = 36,
                     LargFxTrans = 3.60,
                     LargAcoExtD = 0,
                     LargAcoExtA = 3.00,
                     LargAcoIntDuasFxMin = 0.60,
                     LargAcoIntDuasFxMax = 1.20,
                     LargAcoIntTresFxMin = 2.00,
                     LargAcoIntTresFxMax = 2.50,
                     LargAcoIntQuatroFxMin = 2.50,
                     LargAcoIntQuatroFxMax = 3.00,
                     GabVertD = 0,
                     GabVertA = 5.50,
                     AfastMinBordAcoObC = 0.50,
                     AfastMinBordAcoObI = 1.50,
                     LargCantCentDMin = 10,
                     LargCantCentDMax = 18,
                     LargCantCentNMin = 6,
                     LargCantCentNMax = 7,
                     LargCantCentAMin = 3,
                     LargCantCentAMax = 7
                 },
                 new ClasseDeProjeto()
                 {
                     Id = 3,
                     Nome = "0",
                     Caracteristicas = "Via Expressa - Controle Total de Acessos",
                     CritClassTecnica = "Decisão Administrativa",
                     Relevo = ClasseDeProjeto.TiposDeRelevo.Montanhoso,
                     VelProjeto = 80,
                     VelDirMin = 80,
                     DistMinVisbParMinD = 140,
                     DistMinVisbParMinA = 110,
                     DistMinVisbUltra = 0,
                     RaioMinSupEleMax = 210,
                     SupEleMax = 10,
                     RampaMax = 5,
                     KCxMinD = 48,
                     KCxMinA = 29,
                     KCvMinD = 32,
                     KCvMinA = 24,
                     LargFxTrans = 3.60,
                     LargAcoExtD = 0,
                     LargAcoExtA = 3.00,
                     LargAcoIntDuasFxMin = 0.50,
                     LargAcoIntDuasFxMax = 0.60,
                     LargAcoIntTresFxMin = 2.00,
                     LargAcoIntTresFxMax = 2.50,
                     LargAcoIntQuatroFxMin = 2.50,
                     LargAcoIntQuatroFxMax = 3.00,
                     GabVertD = 0,
                     GabVertA = 5.50,
                     AfastMinBordAcoObC = 0.50,
                     AfastMinBordAcoObI = 1.50,
                     LargCantCentDMin = 10,
                     LargCantCentDMax = 18,
                     LargCantCentNMin = 6,
                     LargCantCentNMax = 7,
                     LargCantCentAMin = 3,
                     LargCantCentAMax = 7
                 },
                 new ClasseDeProjeto()
                 {
                     Id = 4,
                     Nome = "I-A",
                     Caracteristicas = "Pista Dupla - Controle Parcial de Acessos",
                     CritClassTecnica = "Quando o projeto em pista simples resulta em níveis de serviço inferiores ao aceitável",
                     Relevo = ClasseDeProjeto.TiposDeRelevo.Plano,
                     VelProjeto = 100,
                     VelDirMin = 100,
                     DistMinVisbParMinD = 210,
                     DistMinVisbParMinA = 155,
                     DistMinVisbUltra = 680,
                     RaioMinSupEleMax = 345,
                     SupEleMax = 10,
                     RampaMax = 3,
                     KCxMinD = 107,
                     KCxMinA = 58,
                     KCvMinD = 52,
                     KCvMinA = 36,
                     LargFxTrans = 3.60,
                     LargAcoExtD = 0,
                     LargAcoExtA = 3.50,
                     LargAcoIntDuasFxMin = 0.60,
                     LargAcoIntDuasFxMax = 1.20,
                     LargAcoIntTresFxMin = 2.50,
                     LargAcoIntTresFxMax = 3.00,
                     LargAcoIntQuatroFxMin = 3.00,
                     LargAcoIntQuatroFxMax = 3.00,
                     GabVertD = 0,
                     GabVertA = 5.50,
                     AfastMinBordAcoObC = 0.50,
                     AfastMinBordAcoObI = 1.50,
                     LargCantCentDMin = 10,
                     LargCantCentDMax = 12,
                     LargCantCentNMin = 6,
                     LargCantCentNMax = 10,
                     LargCantCentAMin = 3,
                     LargCantCentAMax = 7
                 }, new ClasseDeProjeto()
                 {
                     Id = 5,
                     Nome = "I-A",
                     Caracteristicas = "Pista Dupla - Controle Parcial de Acessos",
                     CritClassTecnica = "Quando o projeto em pista simples resulta em níveis de serviço inferiores ao aceitável",
                     Relevo = ClasseDeProjeto.TiposDeRelevo.Ondulado,
                     VelProjeto = 80,
                     VelDirMin = 80,
                     DistMinVisbParMinD = 140,
                     DistMinVisbParMinA = 110,
                     DistMinVisbUltra = 560,
                     RaioMinSupEleMax = 210,
                     SupEleMax = 10,
                     RampaMax = 4.50,
                     KCxMinD = 48,
                     KCxMinA = 29,
                     KCvMinD = 32,
                     KCvMinA = 24,
                     LargFxTrans = 3.60,
                     LargAcoExtD = 0,
                     LargAcoExtA = 2.50,
                     LargAcoIntDuasFxMin = 0.60,
                     LargAcoIntDuasFxMax = 1.20,
                     LargAcoIntTresFxMin = 2.00,
                     LargAcoIntTresFxMax = 2.50,
                     LargAcoIntQuatroFxMin = 2.50,
                     LargAcoIntQuatroFxMax = 3.00,
                     GabVertD = 0,
                     GabVertA = 5.50,
                     AfastMinBordAcoObC = 0.50,
                     AfastMinBordAcoObI = 1.50,
                     LargCantCentDMin = 10,
                     LargCantCentDMax = 12,
                     LargCantCentNMin = 6,
                     LargCantCentNMax = 10,
                     LargCantCentAMin = 3,
                     LargCantCentAMax = 7
                 }, new ClasseDeProjeto()
                 {
                     Id = 6,
                     Nome = "I-A",
                     Caracteristicas = "Pista Dupla - Controle Parcial de Acessos",
                     CritClassTecnica = "Quando o projeto em pista simples resulta em níveis de serviço inferiores ao aceitável",
                     Relevo = ClasseDeProjeto.TiposDeRelevo.Montanhoso,
                     VelProjeto = 60,
                     VelDirMin = 60,
                     DistMinVisbParMinD = 85,
                     DistMinVisbParMinA = 75,
                     DistMinVisbUltra = 420,
                     RaioMinSupEleMax = 115,
                     SupEleMax = 10,
                     RampaMax = 6,
                     KCxMinD = 18,
                     KCxMinA = 14,
                     KCvMinD = 17,
                     KCvMinA = 15,
                     LargFxTrans = 3.60,
                     LargAcoExtD = 0,
                     LargAcoExtA = 2.50,
                     LargAcoIntDuasFxMin = 0.50,
                     LargAcoIntDuasFxMax = 0.60,
                     LargAcoIntTresFxMin = 2.00,
                     LargAcoIntTresFxMax = 2.50,
                     LargAcoIntQuatroFxMin = 2.50,
                     LargAcoIntQuatroFxMax = 3.00,
                     GabVertD = 0,
                     GabVertA = 5.50,
                     AfastMinBordAcoObC = 0.50,
                     AfastMinBordAcoObI = 1.50,
                     LargCantCentDMin = 10,
                     LargCantCentDMax = 12,
                     LargCantCentNMin = 6,
                     LargCantCentNMax = 10,
                     LargCantCentAMin = 3,
                     LargCantCentAMax = 7
                 }, new ClasseDeProjeto()
                 {
                     Id = 7,
                     Nome = "II",
                     Caracteristicas = "Pista Simples",
                     CritClassTecnica = "Volume de Tráfego projetado: >200 vph ou >1400 vpd ",
                     Relevo = ClasseDeProjeto.TiposDeRelevo.Plano,
                     VelProjeto = 100,
                     VelDirMin = 100,
                     DistMinVisbParMinD = 210,
                     DistMinVisbParMinA = 155,
                     DistMinVisbUltra = 680,
                     RaioMinSupEleMax = 375,
                     SupEleMax = 8,
                     RampaMax = 3,
                     KCxMinD = 107,
                     KCxMinA = 58,
                     KCvMinD = 52,
                     KCvMinA = 36,
                     LargFxTrans = 3.60,
                     LargAcoExtD = 0,
                     LargAcoExtA = 2.50,
                     LargAcoIntDuasFxMin = 0,
                     LargAcoIntDuasFxMax = 0,
                     LargAcoIntTresFxMin = 0,
                     LargAcoIntTresFxMax = 0,
                     LargAcoIntQuatroFxMin = 0,
                     LargAcoIntQuatroFxMax = 0,
                     GabVertD = 5.50,
                     GabVertA = 4.5,
                     AfastMinBordAcoObC = 0.50,
                     AfastMinBordAcoObI = 1.50,
                     LargCantCentDMin = 0,
                     LargCantCentDMax = 0,
                     LargCantCentNMin = 0,
                     LargCantCentNMax = 0,
                     LargCantCentAMin = 0,
                     LargCantCentAMax = 0
                 }, new ClasseDeProjeto()
                 {
                     Id = 8,
                     Nome = "II",
                     Caracteristicas = "Pista Simples",
                     CritClassTecnica = "Volume de Tráfego projetado: >200 vph ou >1400 vpd ",
                     Relevo = ClasseDeProjeto.TiposDeRelevo.Montanhoso,
                     VelProjeto = 70,
                     VelDirMin = 70,
                     DistMinVisbParMinD = 110,
                     DistMinVisbParMinA = 90,
                     DistMinVisbUltra = 490,
                     RaioMinSupEleMax = 170,
                     SupEleMax = 8,
                     RampaMax = 5,
                     KCxMinD = 29,
                     KCxMinA = 20,
                     KCvMinD = 24,
                     KCvMinA = 19,
                     LargFxTrans = 3.60,
                     LargAcoExtD = 0,
                     LargAcoExtA = 2.50,
                     LargAcoIntDuasFxMin = 0,
                     LargAcoIntDuasFxMax = 0,
                     LargAcoIntTresFxMin = 0,
                     LargAcoIntTresFxMax = 0,
                     LargAcoIntQuatroFxMin = 0,
                     LargAcoIntQuatroFxMax = 0,
                     GabVertD = 5.50,
                     GabVertA = 4.5,
                     AfastMinBordAcoObC = 0.50,
                     AfastMinBordAcoObI = 1.50,
                     LargCantCentDMin = 0,
                     LargCantCentDMax = 0,
                     LargCantCentNMin = 0,
                     LargCantCentNMax = 0,
                     LargCantCentAMin = 0,
                     LargCantCentAMax = 0
                 }, new ClasseDeProjeto()
                 {
                     Id = 9,
                     Nome = "II",
                     Caracteristicas = "Pista Simples",
                     CritClassTecnica = "Volume de Tráfego projetado: >200 vph ou >1400 vpd ",
                     Relevo = ClasseDeProjeto.TiposDeRelevo.Montanhoso,
                     VelProjeto = 50,
                     VelDirMin = 50,
                     DistMinVisbParMinD = 65,
                     DistMinVisbParMinA = 60,
                     DistMinVisbUltra = 350,
                     RaioMinSupEleMax = 80,
                     SupEleMax = 8,
                     RampaMax = 7,
                     KCxMinD = 10,
                     KCxMinA = 9,
                     KCvMinD = 12,
                     KCvMinA = 11,
                     LargFxTrans = 3.30,
                     LargAcoExtD = 0,
                     LargAcoExtA = 2.00,
                     LargAcoIntDuasFxMin = 0,
                     LargAcoIntDuasFxMax = 0,
                     LargAcoIntTresFxMin = 0,
                     LargAcoIntTresFxMax = 0,
                     LargAcoIntQuatroFxMin = 0,
                     LargAcoIntQuatroFxMax = 0,
                     GabVertD = 5.50,
                     GabVertA = 4.5,
                     AfastMinBordAcoObC = 0.50,
                     AfastMinBordAcoObI = 1.50,
                     LargCantCentDMin = 0,
                     LargCantCentDMax = 0,
                     LargCantCentNMin = 0,
                     LargCantCentNMax = 0,
                     LargCantCentAMin = 0,
                     LargCantCentAMax = 0
                 }, new ClasseDeProjeto()
                 {
                     Id = 10,
                     Nome = "III",
                     Caracteristicas = "Pista Simples",
                     CritClassTecnica = "Volume de Tráfego projetado: 300 a 700 vpd ",
                     Relevo = ClasseDeProjeto.TiposDeRelevo.Plano,
                     VelProjeto = 80,
                     VelDirMin = 80,
                     DistMinVisbParMinD = 140,
                     DistMinVisbParMinA = 110,
                     DistMinVisbUltra = 560,
                     RaioMinSupEleMax = 230,
                     SupEleMax = 8,
                     RampaMax = 4,
                     KCxMinD = 48,
                     KCxMinA = 29,
                     KCvMinD = 32,
                     KCvMinA = 24,
                     LargFxTrans = 3.50,
                     LargAcoExtD = 0,
                     LargAcoExtA = 2.50,
                     LargAcoIntDuasFxMin = 0,
                     LargAcoIntDuasFxMax = 0,
                     LargAcoIntTresFxMin = 0,
                     LargAcoIntTresFxMax = 0,
                     LargAcoIntQuatroFxMin = 0,
                     LargAcoIntQuatroFxMax = 0,
                     GabVertD = 5.50,
                     GabVertA = 4.5,
                     AfastMinBordAcoObC = 0.30,
                     AfastMinBordAcoObI = 0.50,
                     LargCantCentDMin = 0,
                     LargCantCentDMax = 0,
                     LargCantCentNMin = 0,
                     LargCantCentNMax = 0,
                     LargCantCentAMin = 0,
                     LargCantCentAMax = 0
                 }, new ClasseDeProjeto()
                 {
                     Id = 11,
                     Nome = "III",
                     Caracteristicas = "Pista Simples",
                     CritClassTecnica = "Volume de Tráfego projetado: 300 a 700 vpd ",
                     Relevo = ClasseDeProjeto.TiposDeRelevo.Ondulado,
                     VelProjeto = 60,
                     VelDirMin = 60,
                     DistMinVisbParMinD = 85,
                     DistMinVisbParMinA = 75,
                     DistMinVisbUltra = 420,
                     RaioMinSupEleMax = 125,
                     SupEleMax = 8,
                     RampaMax = 6,
                     KCxMinD = 18,
                     KCxMinA = 14,
                     KCvMinD = 17,
                     KCvMinA = 15,
                     LargFxTrans = 3.30,
                     LargAcoExtD = 0,
                     LargAcoExtA = 2.00,
                     LargAcoIntDuasFxMin = 0,
                     LargAcoIntDuasFxMax = 0,
                     LargAcoIntTresFxMin = 0,
                     LargAcoIntTresFxMax = 0,
                     LargAcoIntQuatroFxMin = 0,
                     LargAcoIntQuatroFxMax = 0,
                     GabVertD = 5.50,
                     GabVertA = 4.5,
                     AfastMinBordAcoObC = 0.30,
                     AfastMinBordAcoObI = 0.50,
                     LargCantCentDMin = 0,
                     LargCantCentDMax = 0,
                     LargCantCentNMin = 0,
                     LargCantCentNMax = 0,
                     LargCantCentAMin = 0,
                     LargCantCentAMax = 0
                 }, new ClasseDeProjeto()
                 {
                     Id = 12,
                     Nome = "III",
                     Caracteristicas = "Pista Simples",
                     CritClassTecnica = "Volume de Tráfego projetado: 300 a 700 vpd ",
                     Relevo = ClasseDeProjeto.TiposDeRelevo.Montanhoso,
                     VelProjeto = 40,
                     VelDirMin = 40,
                     DistMinVisbParMinD = 45,
                     DistMinVisbParMinA = 45,
                     DistMinVisbUltra = 270,
                     RaioMinSupEleMax = 50,
                     SupEleMax = 8,
                     RampaMax = 8,
                     KCxMinD = 5,
                     KCxMinA = 5,
                     KCvMinD = 7,
                     KCvMinA = 7,
                     LargFxTrans = 3.30,
                     LargAcoExtD = 0,
                     LargAcoExtA = 1.50,
                     LargAcoIntDuasFxMin = 0,
                     LargAcoIntDuasFxMax = 0,
                     LargAcoIntTresFxMin = 0,
                     LargAcoIntTresFxMax = 0,
                     LargAcoIntQuatroFxMin = 0,
                     LargAcoIntQuatroFxMax = 0,
                     GabVertD = 5.50,
                     GabVertA = 4.5,
                     AfastMinBordAcoObC = 0.30,
                     AfastMinBordAcoObI = 0.50,
                     LargCantCentDMin = 0,
                     LargCantCentDMax = 0,
                     LargCantCentNMin = 0,
                     LargCantCentNMax = 0,
                     LargCantCentAMin = 0,
                     LargCantCentAMax = 0
                 }, new ClasseDeProjeto()
                 {
                     Id = 13,
                     Nome = "IV-A",
                     Caracteristicas = "Pista Simples",
                     CritClassTecnica = "Tráfego na data de abertura: 50 a 200 vpd ",
                     Relevo = ClasseDeProjeto.TiposDeRelevo.Plano,
                     VelProjeto = 60,
                     VelDirMin = 60,
                     DistMinVisbParMinD = 85,
                     DistMinVisbParMinA = 75,
                     DistMinVisbUltra = 420,
                     RaioMinSupEleMax = 125,
                     SupEleMax = 8,
                     RampaMax = 4,
                     KCxMinD = 18,
                     KCxMinA = 14,
                     KCvMinD = 17,
                     KCvMinA = 15,
                     LargFxTrans = 3.00,
                     LargAcoExtD = 0,
                     LargAcoExtA = 1.30,
                     LargAcoIntDuasFxMin = 0,
                     LargAcoIntDuasFxMax = 0,
                     LargAcoIntTresFxMin = 0,
                     LargAcoIntTresFxMax = 0,
                     LargAcoIntQuatroFxMin = 0,
                     LargAcoIntQuatroFxMax = 0,
                     GabVertD = 5.50,
                     GabVertA = 4.5,
                     AfastMinBordAcoObC = 0.30,
                     AfastMinBordAcoObI = 0.50,
                     LargCantCentDMin = 0,
                     LargCantCentDMax = 0,
                     LargCantCentNMin = 0,
                     LargCantCentNMax = 0,
                     LargCantCentAMin = 0,
                     LargCantCentAMax = 0
                 }, new ClasseDeProjeto()
                 {
                     Id = 14,
                     Nome = "IV-A",
                     Caracteristicas = "Pista Simples",
                     CritClassTecnica = "Tráfego na data de abertura: 50 a 200 vpd ",
                     Relevo = ClasseDeProjeto.TiposDeRelevo.Ondulado,
                     VelProjeto = 40,
                     VelDirMin = 40,
                     DistMinVisbParMinD = 48,
                     DistMinVisbParMinA = 45,
                     DistMinVisbUltra = 270,
                     RaioMinSupEleMax = 50,
                     SupEleMax = 8,
                     RampaMax = 6,
                     KCxMinD = 5,
                     KCxMinA = 5,
                     KCvMinD = 2,
                     KCvMinA = 2,
                     LargFxTrans = 3.00,
                     LargAcoExtD = 0,
                     LargAcoExtA = 1.30,
                     LargAcoIntDuasFxMin = 0,
                     LargAcoIntDuasFxMax = 0,
                     LargAcoIntTresFxMin = 0,
                     LargAcoIntTresFxMax = 0,
                     LargAcoIntQuatroFxMin = 0,
                     LargAcoIntQuatroFxMax = 0,
                     GabVertD = 5.50,
                     GabVertA = 4.5,
                     AfastMinBordAcoObC = 0.30,
                     AfastMinBordAcoObI = 0.50,
                     LargCantCentDMin = 0,
                     LargCantCentDMax = 0,
                     LargCantCentNMin = 0,
                     LargCantCentNMax = 0,
                     LargCantCentAMin = 0,
                     LargCantCentAMax = 0
                 }, new ClasseDeProjeto()
                 {
                     Id = 15,
                     Nome = "IV-A",
                     Caracteristicas = "Pista Simples",
                     CritClassTecnica = "Tráfego na data de abertura: 50 a 200 vpd ",
                     Relevo = ClasseDeProjeto.TiposDeRelevo.Montanhoso,
                     VelProjeto = 30,
                     VelDirMin = 30,
                     DistMinVisbParMinD = 30,
                     DistMinVisbParMinA = 30,
                     DistMinVisbUltra = 180,
                     RaioMinSupEleMax = 25,
                     SupEleMax = 8,
                     RampaMax = 8,
                     KCxMinD = 2,
                     KCxMinA = 2,
                     KCvMinD = 4,
                     KCvMinA = 4,
                     LargFxTrans = 3.00,
                     LargAcoExtD = 0,
                     LargAcoExtA = 0.80,
                     LargAcoIntDuasFxMin = 0,
                     LargAcoIntDuasFxMax = 0,
                     LargAcoIntTresFxMin = 0,
                     LargAcoIntTresFxMax = 0,
                     LargAcoIntQuatroFxMin = 0,
                     LargAcoIntQuatroFxMax = 0,
                     GabVertD = 5.50,
                     GabVertA = 4.5,
                     AfastMinBordAcoObC = 0.30,
                     AfastMinBordAcoObI = 0.50,
                     LargCantCentDMin = 0,
                     LargCantCentDMax = 0,
                     LargCantCentNMin = 0,
                     LargCantCentNMax = 0,
                     LargCantCentAMin = 0,
                     LargCantCentAMax = 0
                 }, new ClasseDeProjeto()
                 {
                     Id = 16,
                     Nome = "IV-B",
                     Caracteristicas = "Pista Simples",
                     CritClassTecnica = "Tráfego na data de abertura: < 50 vpd ",
                     Relevo = ClasseDeProjeto.TiposDeRelevo.Plano,
                     VelProjeto = 60,
                     VelDirMin = 60,
                     DistMinVisbParMinD = 85,
                     DistMinVisbParMinA = 75,
                     DistMinVisbUltra = 420,
                     RaioMinSupEleMax = 125,
                     SupEleMax = 8,
                     RampaMax = 6,
                     KCxMinD = 18,
                     KCxMinA = 14,
                     KCvMinD = 17,
                     KCvMinA = 15,
                     LargFxTrans = 2.50,
                     LargAcoExtD = 0,
                     LargAcoExtA = 1.00,
                     LargAcoIntDuasFxMin = 0,
                     LargAcoIntDuasFxMax = 0,
                     LargAcoIntTresFxMin = 0,
                     LargAcoIntTresFxMax = 0,
                     LargAcoIntQuatroFxMin = 0,
                     LargAcoIntQuatroFxMax = 0,
                     GabVertD = 5.50,
                     GabVertA = 4.5,
                     AfastMinBordAcoObC = 0.30,
                     AfastMinBordAcoObI = 0.50,
                     LargCantCentDMin = 0,
                     LargCantCentDMax = 0,
                     LargCantCentNMin = 0,
                     LargCantCentNMax = 0,
                     LargCantCentAMin = 0,
                     LargCantCentAMax = 0
                 }, new ClasseDeProjeto()
                 {
                     Id = 17,
                     Nome = "IV-B",
                     Caracteristicas = "Pista Simples",
                     CritClassTecnica = "Tráfego na data de abertura: < 50 vpd  ",
                     Relevo = ClasseDeProjeto.TiposDeRelevo.Ondulado,
                     VelProjeto = 40,
                     VelDirMin = 40,
                     DistMinVisbParMinD = 48,
                     DistMinVisbParMinA = 45,
                     DistMinVisbUltra = 270,
                     RaioMinSupEleMax = 50,
                     SupEleMax = 8,
                     RampaMax = 8,
                     KCxMinD = 5,
                     KCxMinA = 5,
                     KCvMinD = 2,
                     KCvMinA = 2,
                     LargFxTrans = 2.50,
                     LargAcoExtD = 0,
                     LargAcoExtA = 1.00,
                     LargAcoIntDuasFxMin = 0,
                     LargAcoIntDuasFxMax = 0,
                     LargAcoIntTresFxMin = 0,
                     LargAcoIntTresFxMax = 0,
                     LargAcoIntQuatroFxMin = 0,
                     LargAcoIntQuatroFxMax = 0,
                     GabVertD = 5.50,
                     GabVertA = 4.5,
                     AfastMinBordAcoObC = 0.30,
                     AfastMinBordAcoObI = 0.50,
                     LargCantCentDMin = 0,
                     LargCantCentDMax = 0,
                     LargCantCentNMin = 0,
                     LargCantCentNMax = 0,
                     LargCantCentAMin = 0,
                     LargCantCentAMax = 0
                 }, new ClasseDeProjeto()
                 {
                     Id = 18,
                     Nome = "IV-B",
                     Caracteristicas = "Pista Simples",
                     CritClassTecnica = "Tráfego na data de abertura: < 50 vpd  ",
                     Relevo = ClasseDeProjeto.TiposDeRelevo.Montanhoso,
                     VelProjeto = 30,
                     VelDirMin = 30,
                     DistMinVisbParMinD = 30,
                     DistMinVisbParMinA = 30,
                     DistMinVisbUltra = 180,
                     RaioMinSupEleMax = 25,
                     SupEleMax = 8,
                     RampaMax = 10,
                     KCxMinD = 2,
                     KCxMinA = 2,
                     KCvMinD = 4,
                     KCvMinA = 4,
                     LargFxTrans = 2.50,
                     LargAcoExtD = 0,
                     LargAcoExtA = 0.50,
                     LargAcoIntDuasFxMin = 0,
                     LargAcoIntDuasFxMax = 0,
                     LargAcoIntTresFxMin = 0,
                     LargAcoIntTresFxMax = 0,
                     LargAcoIntQuatroFxMin = 0,
                     LargAcoIntQuatroFxMax = 0,
                     GabVertD = 5.50,
                     GabVertA = 4.5,
                     AfastMinBordAcoObC = 0.30,
                     AfastMinBordAcoObI = 0.50,
                     LargCantCentDMin = 0,
                     LargCantCentDMax = 0,
                     LargCantCentNMin = 0,
                     LargCantCentNMax = 0,
                     LargCantCentAMin = 0,
                     LargCantCentAMax = 0
                 }



             );

            context.Claims.AddOrUpdate(c => c.Name,
                new Claims()
                {
                    Name = "InstituicaoDeEnsino",
                    Id = 1
                },
                new Claims()
                {
                    Name = "Nome",
                    Id = 2
                }, new Claims()
                {
                    Name = "Sobrenome",
                    Id = 3
                }


            );

            context.SaveChanges();

            context.Users.AddOrUpdate(u => u.UserName,
                //Admin do Sistema
                new ApplicationUser()
                {
                    Email = "vinicius@viniro.me",
                    UserName = "vinicius@viniro.me",
                    Id = 1,
                    PasswordHash = "AKziDHvcjobhWAQt8FgDzooKQB7Olb5C0pW7+QBEdSdKyZYStOJL/p4HYOSYVqYH2Q==",
                    SecurityStamp = "d532c7e5-f530-4d7d-a7c0-ae6791d57298",
                    PhoneNumber = null,
                    PhoneNumberConfirmed = false,
                    TwoFactorEnabled = false,
                    LockoutEndDateUtc = null,
                    LockoutEnabled = true,
                    AccessFailedCount = 0

                });

            context.SaveChanges();

            var userStore = new UserStoreIntPk(context);
            var userManager = new UserManager<ApplicationUser, int>(userStore);
            //Claims de Admin

            if (!userManager.GetClaims(1).Any(x => x.Type == "InstituicaoDeEnsino"))
            {
                userManager.AddClaim(1, new Claim("InstituicaoDeEnsino", "UERJ"));
            }
            if (!userManager.GetClaims(1).Any(x => x.Type == "Nome"))
            {
                userManager.AddClaim(1, new Claim("Nome", "Vinicius"));
            }
            if (!userManager.GetClaims(1).Any(x => x.Type == "Sobrenome"))
            {
                userManager.AddClaim(1, new Claim("Sobrenome", "Rodrigues"));
            }

            context.SaveChanges();

            context.Projetos.AddOrUpdate(x => x.Id,
                new Projeto()
                {
                    Id = 1,
                    Nome = "Projeto de Teste",
                    ClasseDeProjeto = context.ClasseDeProjetos.Find(7),
                    CoordenadasReais = true,
                    DateIncluded = new DateTime(2017, 10, 19),
                    DateAltered = new DateTime(2017, 10, 19),
                    MapaRenderizado = false,
                    PontosNotaveis = new List<PontoNotavel>(),
                    User = context.Users.Find(1)
                });
            context.SaveChanges();
            context.PontosNotaveis.AddOrUpdate(x => x.Id,
                new PontoNotavel() { Nome = "PI", Projeto = context.Projetos.Find(1), Id = 1, Coordenada = new Coordenada(666891.61, 7497073.31, 14, 23, "K") },
                new PontoNotavel() { Nome = "P1", Projeto = context.Projetos.Find(1), Id = 2, Coordenada = new Coordenada(670049.16, 7499272.30, 31.003108978271481, 23, "K") },
                new PontoNotavel() { Nome = "P2", Projeto = context.Projetos.Find(1), Id = 3, Coordenada = new Coordenada(671607.06, 7498665.60, 17.667909622192379, 23, "K") },
                new PontoNotavel() { Nome = "P3", Projeto = context.Projetos.Find(1), Id = 4, Coordenada = new Coordenada(674587.76, 7501793.01, 26.687429428100589, 23, "K") },
                new PontoNotavel() { Nome = "P4", Projeto = context.Projetos.Find(1), Id = 5, Coordenada = new Coordenada(676626.06, 7501921.06, 27.280202865600589, 23, "K") },
                new PontoNotavel() { Nome = "P5", Projeto = context.Projetos.Find(1), Id = 6, Coordenada = new Coordenada(676715.81, 7503509.80, 33.147274017333977, 23, "K") },
                new PontoNotavel() { Nome = "P6", Projeto = context.Projetos.Find(1), Id = 7, Coordenada = new Coordenada(677001.45, 7504498.42, 48.951969146728523, 23, "K") },
                new PontoNotavel() { Nome = "P7", Projeto = context.Projetos.Find(1), Id = 8, Coordenada = new Coordenada(677346.31, 7504562.68, 67.0234146118164, 23, "K") },
                new PontoNotavel() { Nome = "PF", Projeto = context.Projetos.Find(1), Id = 9, Coordenada = new Coordenada(678416.84, 7505825.10, 93.370201110839844, 23, "K") }
                );

            context.SaveChanges();
            context.Projetos.AddOrUpdate(x => x.Id,
                new Projeto()
                {
                    Id = 2,
                    Nome = "Projeto de Teste - Espiral",
                    ClasseDeProjeto = context.ClasseDeProjetos.Find(4),
                    CoordenadasReais = true,
                    DateIncluded = new DateTime(2017, 11, 15),
                    DateAltered = new DateTime(2017, 11, 15),
                    MapaRenderizado = false,
                    PontosNotaveis = new List<PontoNotavel>(),
                    User = context.Users.Find(1)
                });
            context.SaveChanges();
            context.PontosNotaveis.AddOrUpdate(x => x.Id,
                new PontoNotavel() { Nome = "PI", Projeto = context.Projetos.Find(2), Id = 10, Coordenada = new Coordenada(666973.8190, 7498799.1760, 82.04954528808594, 23, "K") },
                new PontoNotavel() { Nome = "P1", Projeto = context.Projetos.Find(2), Id = 11, Coordenada = new Coordenada(667762.7437, 7500284.9613, 47.526893615722, 23, "K") },
                new PontoNotavel() { Nome = "P2", Projeto = context.Projetos.Find(2), Id = 12, Coordenada = new Coordenada(670318.5929, 7500426.8699, 71.0493011474609, 23, "K") },
                new PontoNotavel() { Nome = "P3", Projeto = context.Projetos.Find(2), Id = 13, Coordenada = new Coordenada(671764.3258, 7501549.2375, 157.668365478515, 23, "K") },
                new PontoNotavel() { Nome = "P4", Projeto = context.Projetos.Find(2), Id = 14, Coordenada = new Coordenada(673248.7836, 7501671.7949, 212.8894500732422, 23, "K") },
                new PontoNotavel() { Nome = "PF", Projeto = context.Projetos.Find(2), Id = 18, Coordenada = new Coordenada(674734.7350, 7503093.0150, 168.4508514404297, 23, "K") }
            );

            context.SaveChanges();
        }
    }
}
